# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 08:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='\u0411\u043e\u0440\u0442\u043e\u0432\u043e\u0439 \u043d\u043e\u043c\u0435\u0440')),
                ('current_load', models.PositiveIntegerField(default=0, verbose_name='\u0422\u0435\u043a\u0443\u0449\u0430\u044f \u0437\u0430\u0433\u0440\u0443\u0437\u043a\u0430')),
            ],
        ),
        migrations.CreateModel(
            name='TruckModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=16, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('capacity', models.PositiveIntegerField(verbose_name='\u041c\u0430\u043a\u0441. \u0437\u0430\u0433\u0440\u0443\u0437\u043a\u0430')),
            ],
        ),
        migrations.AddField(
            model_name='truck',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quarry.TruckModel', verbose_name='\u041c\u043e\u0434\u0435\u043b\u044c'),
        ),
    ]
